### ISSUE TITLE
Add wrapper class which allows "timeout" rejection handling

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#135]
This would make the thread pool limiters a ton more useful, though it could be useful to any thread pool in general.

The idea is this, a task is sent for execution on a thread pool.  Either the limiter is reducing concurrency, or the thread pools threads are all consumed.  Eventually we would want to handle a timeout case.  This would entail an interface calling on to the object so that it can handle the timeout in an application specific way (the most obvious one would be perhaps respond to a waiting client connection to say that a timeout occurred).

I might see if we can make two implementations (one that would extend the other).  One would timeout before any generic resource is provided (ie a thread as described above, or possible a request to an external API).  And one which is specific to the Executor interface.  I am unsure if this makes sense or not right now, just throwing ideas out there.

Unfortunately in order to be able to reliably handle the timeout cases this implementation will need a thread of its own.

**Comment by lwahlmeier** [comment]
I think for now we should solve it in a generic way, allowing the implementer to set the threadPool, docing that it might be an issue if they use the same threadPool they are putting tasks on as they might block the timeouts.  

I personally dont feel that the watchdog should be responsible for interrupting the thread, it should simply just let you know your timer for task X was hit allowing you do do what you need to with it at that point.

Is there a simple way to interrupt a currently running run on a thread in a threadly threadpool?

**Comment by jentfoo** [comment]
The answer is sorta....In a normal thread pool a returned future has the ability to "cancel" which accepts a boolean if the running thread should have an interrupt sent to it.

I guess I was attempting something else which is to set a timeout as an error, rather than canceling that.  So with the current design proposal we can only work with SettableListenableFuture's.

I am now wondering if it makes more sense to just call cancel on the future instead, and accept any future type.  This would mean that if you do a .get() on the future, instead of getting the checked ExecutionException, you would get the unchecked CancellationException (i think that is the type).

Right now SettableListenableFuture's can never be canceled.  I do think we would want to support more future types than just ListenableFutureTask.  Do you think it makes sense to do the above change, AND make SettableListenableFuture's able to be canceled?  In the SLF case, no matter what we could never interrupt a thread, since there is no thread associated with them.  This current watchdog implementation basically adds that association with a SLF and a thread.

I know that's a lot, does all that make sense?

**Comment by lwahlmeier** [comment]
It does mean sense.  I dont think adding cancel to a slf buys us much unless they can share a common interface so we dont have to track both.

I do like the idea of cancel for futureTasks (which interupts the thread) and then for slf we just mark it as error, and only if they provided a thread interupt it.

**Comment by lwahlmeier** [comment]
also was ConcurrentLinkedList the fastest concurrent stucture you could find for this?  and are we sure just syncing on adds/removes on non-concurrent is not faster?

**Comment by jentfoo** [comment]
It depends right...if there is limited concurrent access then the ConcurrentLinkedQueue is faster.  If there is heavy thread contention (ie tons of adding at the same time tons of tasks finishing), then synchronization likely would be faster.

For the real life use cases we have seen so far the ConcurrentLinkedQueue is better.

**Comment by jentfoo** [comment]
So we could have two watchdogs.

One that is "CancelingWatchdog" that would cancel the future.  And one that is "SetTimeoutWatchdog" which would only work on SettableListenableFuture's.

The question is....if you can detect a timeout with a SettableListenableFuture via a cancel (which you can't currently, the behavior would be if no result or error is set, we would set a cancel, and when you do a .get() it would throw a CancellationException just like a normal future would).

Do you see any need in the ability to set a "TimeoutException" as the error.  This TimeoutException would have been wrapped in an ExecutionException like any other error type, so you do have to be aware to attempt to catch this normally unchecked exception.

What do you think?  I thought we would bring the discussion here rather than garbage up your pull request.

**Comment by jentfoo** [comment]
@lwahlmeier here is a possible implementation where we just call .cancel() on the future.  This works with any future type, but instead of getting an ExecutionException on timeout, you would get a CancellationException.  What do you think is better?

https://github.com/jentfoo/threadly/blob/issue135-add_watchdog/src/main/java/org/threadly/concurrent/future/Watchdog.java

Now in order to interrupt a thread with a SettableListeanbleFuture you have to set the thread first by invoking "setRunningThread"  then if you call cancel with a true, it will send an interrupt to that thread.

https://github.com/jentfoo/threadly/blob/issue135-add_watchdog/src/main/java/org/threadly/concurrent/future/SettableListenableFuture.java

Maybe we should have lunch together sometime?  That way we can hammer out some of these details.  I feel like we have a lot to talk about!  Send me an email if your interested in having lunch next week.

**Comment by jentfoo** [comment]
@lwahlmeier  and here is what it looks like right now to use Watchdog in the SSLClient:

https://github.com/jentfoo/litesockets/blob/watchdog_for_timeouts/src/main/java/org/threadly/litesockets/tcp/SSLClient.java

**Comment by jentfoo** [comment]
Closing since this has been merged into unstable staging (as in the 4.0.0-SNAPSHOT artifact).

@lwahlmeier what do you think about the link I posted for using watchdog in litesockets?

I may still want to add "Watchdog"Executors in 4.0.0, but not a requirement for the release.
