### ISSUE TITLE
Should the ability to provide an Executor in the profile be removed in 4.0.0?

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#143]
This would require a 3.9.0 release so we can provide an artifact with the API deprecated.  Here are my thoughts:

* If I were to redo it, I probably would not allow an Executor to keep things simpler

* If we think the behavior when providing an Executor is obvious and what should be expected, then I am fine with the complexity for now.

I would really like your opinion if there is anything confusing about the behavior with the executor (long term thread usage, check if it is a scheduler to schedule a task to stop the profiler, if not provided or scheduler make a second thread to do the stop (assuming a timeout was provided)).

I am really on the fence about it, but it's easy what ever we want to do (we should just decide).

**Comment by lwahlmeier** [comment]
Have you thought about just letting them pass in a scheduler?  if they do the profiler would be able to do everything it needs w/o having to create threads.

**Comment by jentfoo** [comment]
So I did...In order to maintain compatibility with 3.8.0's API I would have to add three functions because I would still need to support the executor interface.  So all that would save me is the instanceof check (which is annoying and not super efficient), but I figured it was not that bad compared to the code that would be needed to accept a scheduler.

**Comment by jentfoo** [comment]
We have decided this will not be removed in 4.X
