### ISSUE TITLE
Consider building a "polling" PriorityScheduler

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#175]
An idea for a new possible scheduler would be one which constantly has threads polling for tasks, rather than going into a blocking state and being alerted/interrupt driven when a task is ready to run.

I wonder if we could possibly archive higher execution throughput if we never park or unpark our worker threads.  Instead they would constantly be polling for work.  The logic paths would be simpler, and we have already had to do a bunch of optimizations around trying to avoid unnecessary unparks, etc.

This would NOT be a replacement for the PriorityScheduler.  Rather just a new pool concept entirely, designed around systems which are expected to be always heavily loaded, and require very high execution throughput.

This would have the massive disadvantage of using 100% of the CPU, even when there is nothing to execute.  For that reason you would probably want the threads to == the number of cores.  In addition there is an energy usage determent, since idle systems would not be able to scale their usage down.

In order to do this, the first step would be removing the task hand off thread in the PriorityScheduler, since worker threads themselves would have to do the polling.  I have a branch where this was stated ( https://github.com/jentfoo/threadly/tree/experimental-PriorityScheduler-no_queue_manager_thread )...but it's not 100% there yet.

**Comment by lwahlmeier** [comment]
Its an interesting Idea.  I dont think it would work if we just spun 100% of the time, but there might be simple cases we can check for and spin while we are in them.  I dont think it would be good to just always spin every thread.  I would limit the spinning thread to just 1 thread at a time, maybe using it as the hand off thread until all other available threads are consumed, then taking a task itself.  Then first thread to finish becomes the spinning thread again.  I also think it would be best to limit how much its allowed to spin, I def think it might be worth wasting some cpu time not parking/waiting, but not forever.

**Comment by jentfoo** [comment]
it only works if every thread spins.  That's why this pool would never want to have more than the available cores for possible threads to run.

A hand off thread would not make sense for this because it would be designed for very high frequency and throughput, so in theory all threads should be consuming tasks in parallel.

In addition if there is going to be any benefit it would have to be from lack of logic around park/unpark.  As soon as we block we have to queue before we can park, check again, then finally park.  In addition the active threads have the burden of waking up the next inactive thread.  So it really only will have a benefit if all threads are always spinning _if there is no work_.

I warrant that this pool wont make sense for 90% of the apps out there.  Most people will want to use the existing PriorityScheduler.  But this could be a really cool tool for that 10%...if the numbers prove the theories.

**Comment by lwahlmeier** [comment]
I do think there is an advantage in spinning a little more and not parking so fast, but I would argue that if all threads in the pool spin that is would be less then 1% of any threadpool implementation that would ever want it.  I mean it would only ever benifit a threadpool that is never not working, even if a threadpool is busy 99.9% of the time, over time that .1% becomes so much time it was cheaper over the long haul to park/unpark.  There is also a point, at least in linux, where it would be cheaper to just make a new thread for every exec/schedule instead of spinning.

**Comment by jentfoo** [comment]
Yea, I can see where your coming from.  At least initially I think we should start with no parking at all, as little logic, and absolutely as fast as possible.

This is basically only for a pool which is loaded > 90% of the time.  And that 10% of the time, if it's spinning, it would be no different CPU wise from that other 90% of time.  But during that 90%, it would be absolutely as fast as possible.

This does not make sense for loads that change over time/demand.  But rather just very heavy processing focused loads.

I think the first step is even proving the concept even makes sense in (or is even possible) in java.  We need to prove with absolutely no parking that it is faster than the current scheduler.  Then if we can reduce spinning AND not loose any performance, I would be open to it, but I think it's unlikely.  It may be unlikely we will see any advantage even if we have absolutely no parking as it is.

**Comment by jentfoo** [comment]
Well now that we have the new PriorityScheduler in master, I went ahead and did a quick hack job to see if this is even worth perusing.  Ultimately the gains were not nearly as large as I thought they might be (and as you might expect in some cases there are substantial losses).

So I am going to close this as wont fix, there just does not seem to be the theoretical gains that I thought might exist.
