### ISSUE TITLE
Should ListenerHelper use a List of "Pair" instead of a HashMap?

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#177]
In 4.4.0 we are adding a tuple class "Pair".  I looked at possibly using this inside ListenerHelper and RunnableListenableHelper to associate the listener with the Executor it should run on.  Right now a HashMap is being used to handle that association.

I did some quick tests and this would provide a performance boost, and a heap usage improvement with one very large behavior change.  Right now since we use the listener as the key to the map it means if you add a listener twice, the second addition will be ignored...meaning the only way to have a listener to be called twice would be to use something like RunnableChain.  If we switch to using a Pair, it does not make computation sense to check the list for a duplicate entry.  So this behavior would change to adding a listener twice will result in multiple invocations to that listener.

@lwahlmeier this question is mostly directed to you.  Do you think that behavior change when adding a listener multiple times is worth the performance and heap savings?  My instinct says it is.

**Comment by lwahlmeier** [comment]
I think moving to a Pair object makes since, but I do "prefer" the behavior of only being able to add a listener once.  

Where is the performance gain in using a list?  just faster inserts?  Wouldnt a Deque be faster and have everything needed?

**Comment by jentfoo** [comment]
A deque would not be faster.  In general we don't remove listeners, unless it's a one time invokable RunnableListenerHelper, but in that case we drop all of the listeners, so it would not help there either.

If we go to the list design we can't check if the listener is there because doing a linear scan over the list to search for listeners makes us loose any performance gain we might have seen.  Doing a HashMap insertion is way cheaper than a linear scan + list insertion.  But doing a list insertion is the cheapest option, we just loose the behavior around duplicate listeners.

So I think we just need to decide if we want the behavior, or if we want the performance/heap improvements.  I think I would rather have the performance/heap improvements.  I don't feel like inserting listeners multiple times is a very likely behavior issue.

**Comment by lwahlmeier** [comment]
I tend to agree.  I take it just using Pair object and a HashSet is not any better then a HashMap?  I like the behavior of not adding the same listener 2 times, but in general.  Which list are you gonna use?  I know linkedList will have the fastest insert/append times but they actually have pretty big memory over head over ArrayLists.

**Comment by jentfoo** [comment]
Closing this, we will just track this in PR #179
