### ISSUE TITLE
Prototype and benchmark non-fair executor

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#194]
This is an idea I have been mauling over in my head.  I would like to see if we could create an executor with a very fast concurrent structure, but one which is not really a queue.  One which tries to just flow tasks through it as fast as possible, and thus has no guarantees around fairness or starvation.

This obviously would not be to replace our current pools, but to just offer another option.  I am convinced that in 95% of use cases a scheduler like this could likely be used without issue.  But it obviously would only be worth it if the performance is there to justify it.

**Comment by lwahlmeier** [comment]
interesting idea, so it would be just an executor?  no scheduling?

I no one I have seen before that is extremely fast but can get very unfair
is a hashed threadpool.  Basically every thread has its own queue and tasks
get allocated to the queue based on there hashcode.  oddly it works best
with a prime number of threads, and might need a better way to hash then
just the java hashCode to make it fair.  You could probably even do that
with scheduling also if thats needed.  It usually works so well simple
locks around non-concurrent queues work very well, but you might be able to
improve that with cas and memory barriers.

**Comment by jentfoo** [comment]
It would just be an executor, no scheduling.

Hashing for a given thread is an interesting idea.  I had considered that as well before, in theory it could work well for very similar sized tasks.  I considered writing an executor for that design, but in theory the existing KeyDistributedExecutor can provide this advantage without having a more sophisticated pool (because in theory if the pool was fully loaded the KeyDistributedExecutor could potentially never release the thread anyways, and thus we would just use the per-key queues there).

When I originally wrote this I was actually thinking something more like "ConcurrentBag" in HikariCP's pool.  That pool is not fair, basically trying to do queuing as much in thread local as possible, and only going beyond the thread boundary when the thread local queue is empty.

I have written something similar before, but never had a good use for it (at the time I was thinking more for an idle worker queue, but never was able to make it work well enough to justify the complexity).

The key would be, concurrent bag's concepts would work really well if tasks are submitted from other tasks currently running.  But would not work well from a single (or a few limited) threads which are doing all the task submission.  That said, it's worth playing with.

Needless to say, I would like to see how we could get a high performance executor (no scheduling) with lesser guarantees for greater performance.  Not sure exactly what that looks like yet, but I would love to have one that can even blow the doors off PriorityScheduler (for when scheduling is not necessary).

**Comment by jentfoo** [comment]
I thought a bit more about this....maybe a queue per thread makes more sense.  But instead of hashing do round robin distribution.  I also wonder if it might be worth it to allow threads to try and steal from other threads queues if they are completely idle.

Not sure, will need to play with this.

**Comment by jentfoo** [comment]
@lwahlmeier I would love your input on this one.  So I did prototype a quick executor where each thread has its own queue.  At low thread counts it's quite a bit faster, but at high thread counts it's actually slower than java.util.concurrent.  I have not profiled or done much to tune this, just looking for basic ideas.

Here is the parts relevant to task submission:
https://github.com/jentfoo/threadly/blob/unfair_executor/src/main/java/org/threadly/concurrent/UnfairExecutor.java#L44-L67
https://github.com/jentfoo/threadly/blob/unfair_executor/src/main/java/org/threadly/concurrent/UnfairExecutor.java#L109-L120

You can see we just round robin add to tasks to the threads.  Right now there is no attempt to add to the lowest queue or anything like that.
We do have to synchronize at a given threads queue because otherwise I need to figure out a solution of keeping the two structures in sync (nextTaskAddIndex must be incremented once we are able to CAS into the runnable queue...I suppose the alternative would be to cas, and on cas failure retry.  The concern was how do we detect when the queue is full).

Here are the parts for task consumption:
https://github.com/jentfoo/threadly/blob/unfair_executor/src/main/java/org/threadly/concurrent/UnfairExecutor.java#L123-L135

I suspect that the issues are not around task consumption, but rather are around submission.  Let me know if you have any ideas.  I will keep pondering about it as well, and see if I can tinker with it.  FWIW, at low thread counts (< cores * 8) it is about 30% faster than java.util.  And at high thread counts it is about 20% slower, so it definitely looses a lot as thread counts go up.

**Comment by lwahlmeier** [comment]
So I think that might be a good start, I like the AtomicReferenceArray as
the queue, but I do wonder if we could do some form of
AtomicReferenceLinkedList that might work better kind of like what you have
in the PriorityScheduler thread workers.  I think you might also be able to
remove the locking on add if its done right, simple cas loop, and might
even beable to get away with 1 queue, though its hard to say if the cas
operation would spin to much or not.

I also wonder if the performance decrease has to do with the queues being
added to evenly which depending on the load type might be causing them to
go into park/unpark all the time.  I would make sure you have at least 2x
the pending tasks waiting as you have threads.  I do also think it might be
worth at least looking into populating the queues differently, not
necessarily lowest first, but favor adding to queue thats active with 0 vs
one thats parked with 0, to keep from park/unpark as much.
