### ISSUE TITLE
Request for code review on new statistics schedulers/executors

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#197]
I have finished the new statistics schedulers/wrappers for the 4.5.0 release (maybe?).

It's a lot of code, so I did not PR it, it's pretty boring stuff as well, but if you want the full set of code is under the new org.threadly.concurrent.statistics package (all new!):
https://github.com/threadly/threadly/tree/master/src/main/java/org/threadly/concurrent/statistics

@lwahlmeier (or anyone else interested) What I could really use a review on is the two interfaces that all these new schedulers implement:
https://github.com/threadly/threadly/blob/master/src/main/java/org/threadly/concurrent/statistics/StatisticExecutor.java

and

https://github.com/threadly/threadly/blob/master/src/main/java/org/threadly/concurrent/statistics/StatisticPriorityScheduler.java

If you could give it a look soon I would appreciate it.  I am running final stress unit tests, and benchmarks to prepare for the 4.5.0 release.  Once I have those done I want to release 4.5.0 soon (but we need to be sure we are happy with this API since it's new).

If there is any api or javadocs improvements you want post them to this issue.  If you don't see anything go ahead and close this after you have reviewed it.  Thanks!

**Comment by lwahlmeier** [comment]
so in the StatisticPriorityScheduler what does getExecutionDelaySamples() do if called?  is it list of exec times for all queues?  you have overrides with extra discriptions for alot of the other ones, just was not sure about this one.
