### ISSUE TITLE
Lazily create tasks as the queue goes empty

### ISSUE THREAD

**Issue by piegamesde** [threadly/threadly#218]
See [this question](https://stackoverflow.com/q/9590972/6094756) on StackOverflow. Both answers are kind of a hack. Does this library provide a more elegant solution? If yes, how? If no, please add it :)

**Comment by jentfoo** [comment]
There are two ways I would consider recommending doing this:
1) If wanting a small / simple solution that only uses a scheduler.  I would create one task per thread that you want running this load test.  I would then `scheduleWithFixedDelay` each task, providing a delay of `0`.  This will make the task available for execution again immediately after it has just completed.

Only major detail that would need to change is the runnable needs to be capable of multiple executions.  For storing the results the task would need to send them to some concurrent structure (in case the results were previously stored locally to the runnable itself).

2) Second solution I would point to is actually a work in progress library I am making for driving load tests: https://github.com/threadly/ambush

I have not had many other eyes on this library, and so there is probably a fair amount of API improvements to be had.  In addition I need to provide some basic out of the box networking support before I can release 0.1.

But I do use the above to produce very complicated load test patterns.  It does require a lot of memory for larger tests, but you can provide a single step instance to it as many times as you want, and then it will handle storing the results from each execution.

It also tries to be very aware of when objects are being allocated, trying to minimize garbage collection during the test run as much as possible.

I would love to hear any feedback you might have on either of these options.  If you want help using `ambush` feel free to file issues on that project with your questions.

**Comment by piegamesde** [comment]
I had just a quick look at ambush and I think this might be too heavyweight for my situation. Your idea to use a scheduler is really great and I'll try it out, but I wonder what the performance overhead is tough.

I think once I tried different things out and got them running, I'll try to wrap them for library-friendly use (either with a new ExecutorService or a new BlockingList) to add them to this library if you want.

**Comment by jentfoo** [comment]
If you have a lot of load testing needs, then ambush is awesome.  It's able to do way more precise and complex load testing setups, including doing x/sec limits that are independent of your thread scaling.  It's not so much heavy weight as you just have to swallow it's coolaid.

I don't think there is anything like it if you get more complex needs.

If a recurring task performance is not good enough your next step would just be having a while loop in your runnable.

Going to go ahead and close this, but feel free to reply, or open new issues if you think of something specific you want to ask or suggest.
