### ISSUE TITLE
Consider replacing ListenableFuture with java 8's CompletableFuture in v6.0

### ISSUE THREAD

**Issue by jiming** [threadly/threadly#221]
Hi @jentfoo 

Please consider totally support java 8, using CompletableFuture replace ListenableFuture in v6.0.

Thanks!

Jiming

**Comment by jentfoo** [comment]
At a minimum, weather we replace ListenableFuture or not, pre 6.0 we should probably add a compatibility layer as a starting place.  Allowing you to go back and forth potentially between future types.

**Comment by jentfoo** [comment]
We have considered this further and for the time being we want to stick with `ListenableFuture`.  There is still the plans to make a compatibility layer (issue #231), but supporting `CompletableFuture` as the default would result in compromises we don't want to make right now.

`getNumberOfDependents()` in particular would require us to change how we are handling and maintaining our mapping.  Right now I am not seeing any way to support this without incurring at least some minor performance impacts.

Generally there is nothing that you can do with a `CompleteableFuture` that is not support already supported.  I believe our API is simpler and easier to understand.

@jming let me know if you have any new opinions.  Do you think being able to produce a CompleteableFuture from a ListenableFuture would be a good solution?
