### ISSUE TITLE
Look at changing ListenableFuture.ListenerOptimizationStrategy default

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#225]
`ListenerOptimizationStrategy.SingleThreadIfExecutorMatch`/`OrDone` may make sense for 90% of use cases.  With 6.0 allowing API and behavioral changes, we should re-evaluate what we want our default optimization to be like.

**Comment by lwahlmeier** [comment]
I worry there could be unforseen edge cases that could come out of changing the default.  Does changing the default effect unit tests?  None does seem to be the safest, but obviously not the most optimal, I just worry about odd edge cases.

**Comment by jentfoo** [comment]
I agree, moving to 7.X to reconsider then

**Comment by jentfoo** [comment]
Closing for now, the bug #274 to me shows that we are not ready to make this change yet.
