### ISSUE TITLE
Should ThreadFactory's move under their own package

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#229]
`org.threadly.concurrent` always seems like it's getting bloated.  For 6.0 lets see if we want to move thread factories to their own package.

**Comment by jentfoo** [comment]
@lwahlmeier any comment on if we should make this change or just close this issue?

I looked and there are really only two classes we could move (`ConfigurableThreadFactory` and `ThreadReferencingThreadFactory`).  I was not sure what the package name would be, I was thinking maybe just `org.threadly.concurrent.thread`.  I tried to see if there would be anything else we could put under this package, but almost everything we do is at the Runnable level, so I could not find anything else.

Do you think moving those two classes would make the API easier to navigate, or is it not worth changing?

**Comment by lwahlmeier** [comment]
If these would be the only 2 classes I dont think its worth it.

**Comment by jentfoo** [comment]
Sounds good, I could go either way, I am unsure what makes it easiest to navigate the docs and find what you need.

For now I will close this
