### ISSUE TITLE
Should `ListenableFuture` be renamed to `Promise`

### ISSUE THREAD

**Issue by jentfoo** [threadly/threadly#257]
With 6.0 on the horizon, I would like to bring up the former discussion from issue #180 

I don't think the original idea to extend ListenableFuture would work because of the described issues with going back and forth between the interfaces.

We have historically had it where if you are deprecation free at our last version then you for sure would be compatible with the next major release.  This would be a condition where upgrading to 6.0 would simultaneously require code changes.

I do think the `Promise` name would be better, but am unsure if it would be worth the significant heartburn this would cause.  ListenableFuture is one of the more prolific interfaces.

@lwahlmeier What's your vote?  Is the name improvement worth it?  If not, I `promise` I wont bring it up again

@AltSysrq I always appreciate your perspective in ergonomics too

**Comment by lwahlmeier** [comment]
I am not necessarily apposed to the change.  I assume it would still extend `java.util.concurrent.Future`?  I do also think alot of people know the JS promise syntax then/catch/finally:

`https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise`

Would we also want implement those apis? I think it could be a good thing just for easy of use for other people, though I can see how having both could be messy/confusing also.  

I think both names describe what the object is well enough, and I dont really care about class name lengths at all.

**Comment by jentfoo** [comment]
Alright, because of the impact involved lets go ahead and not do this rename right now.  Thanks for the input, if others want to weigh in feel free!
