### ISSUE TITLE
ListenableFuture chain method

### ISSUE THREAD

**Issue by regbo** [threadly/threadly#278]
We spend a lot of time adapting futures, and I think if ListenableFuture had a "chain" method or an "as" method, it would simply a lot of code.

For example, instead of writing:

````java
		CompletableFutureAdapter.toCompletable(future.map(v -> {
			return "example map";
		}).flatMapFailure(Throwable.class, t -> {
			return FutureUtils.immediateResultFuture("example flatMapFailure");
		}));
````

One could use:

````java
		future.map(v -> {
			return "example map";
		}).flatMapFailure(Throwable.class, t -> {
			return FutureUtils.immediateResultFuture("example flatMapFailure");
		}).chain(CompletableFutureAdapter::toCompletable);
````

This could be accomplished by adding the following default method to ListenableFuture:

````java
	default <U> U chain(Function<? super ListenableFuture<T>, U> chainFunction) {
		Objects.requireNonNull(chainFunction);
		return chainFunction.apply(this);
	}
````

Or, to take it further:

````java
	default <U> U chain(Function<? super ListenableFuture<T>, U> chainFunction) {
		Objects.requireNonNull(chainFunction);
		return chainFunction.apply(this);
	}

	default <U, TT extends Throwable> U chainThrowing(
			ChainThrowingFunction<? super ListenableFuture<T>, U, TT> chainFunction)
			throws TT {
		Objects.requireNonNull(chainFunction);
		return chainFunction.apply(this);
	}

	public static interface ChainThrowingFunction<T, R, TT extends Throwable> {

		R apply(T t) throws TT;
	}
````

**Comment by jentfoo** [comment]
Thank you for the recommendation @regbo!  I agree that `chain` would make it much simpler to adapt the futures.

I am less sure in the value of `chainThrowing`.  It seems like throwing at this point is a break of the expected behavior of a future (which should silently contain the failure status).  Is there a specific use case you have in mind where throwing at this point would be useful?

**Comment by regbo** [comment]
>Is there a specific use case you have in mind where throwing at this point would be useful?

I imagine it's not worth it for everyone, but we use ThrowingFunctions for various adaptors, or to do unchecked get()'s with legacy code. Probably too niche of a need.

**Comment by regbo** [comment]
If you need another use caes for the "chain" method, we use it in conjunction with Reactor publishers that can be converted too and from futures. Reactor uses "as", and a stream library we use "StreamEx" uses "chain".

**Comment by jentfoo** [comment]
Thank you @regbo.  I was also considering the specific function name, `as` is more obvious to me what it's designed to do.  If that wording makes sense to you I think `as` is more descriptive.

Would you like to submit a PR for this change, or would you like me to draft this up?  I would like to meet our normal standards for testing and documentation, so I am happy to either help comment on a PR of yours or draft up this change myself.  Thank you!

**Comment by regbo** [comment]
I am a bit strapped for time ATM, so if you could submit the PR that'd be great. I also agree that "as" makes more sense here. Thanks a lot!

**Comment by jentfoo** [comment]
@regbo, I apologize for the delay.  I have submitted this under the PR https://github.com/threadly/threadly/pull/279

If this looks good to you I am happy to release this as version 7.1.  Feel free to leave any suggestions on the PR, thank you!

**Comment by regbo** [comment]
I too was delayed here. Looks great!
