### ISSUE TITLE
Consultation regarding performance

### ISSUE THREAD

**Issue by harsh28799** [threadly/threadly#282]
Hello,

We were looking of a thread management library in java where we can execute summited jobs parallely and should also provide the capability to increase or decrease the number of threads dynamically based on load.
For this requirement we came across threadly and tried testing it with our codebase. Since our requirement involved dynamically changing thread count we choose Priority Scheduler. This was our observations:
1. The time taken and memory requirements for processing were more or less similar when using Priority Scheduler and FixedThreadPoolExecutor.
2. The time taken and memory requirements were more or less similar when using Callable Jobs or Runnable.
3. The number of jobs actually running parallely remains same even with increasing number of threads

Our job has multiple I/O points.

Could you please help us understand if this observation is correct and is expected. Or if we are using it the wrong way. 
Any suggestions or comments is appreciated.

Thank You

**Comment by jentfoo** [comment]
Responded on chat, happy to work through either communication method.  But to share here as well:

My initial question is what does the job load look like when you expand the max pool size? Threads are started lazily, only as there are no other free threads to consume tasks.

By chance are you able to share your example code?

Mike Jensen: If the lazy thread starting is not desired, then I recommend calling this after expanding the pool size: https://threadly.github.io/site/javadocs/threadly/7.0/org/threadly/concurrent/PriorityScheduler.html#prestartAllThreads()

**Comment by jentfoo** [comment]
Discussion has continued on our chat, closing this issue
